configSeat.Sitable = {
	--Only verticalOffset works right now!
	--all scenarios: pastebin.com/6mrYTdQv
	
	-- BENCH (nimkat 2 nafare)
	prop_bench_01a 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_bench_01b 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.45, useOffset = true },
	prop_bench_01c 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.45, useOffset = true },
	prop_bench_02 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_bench_03 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.45, useOffset = true },
	prop_bench_04 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_bench_05 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_bench_06 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_bench_08 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_bench_09 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.31, useOffset = true },
	prop_bench_10 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_bench_11 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.4,  useOffset = true },
	prop_fib_3b_bench 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_ld_bench01 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_wait_bench_01 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },

	-- CHAIR (sandali)
	v_club_stagechair 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	hei_prop_heist_off_chair 	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	hei_prop_hei_skid_chair 	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.1,  useOffset = true },
	prop_chair_01a 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.51, useOffset = true },
	prop_chair_01b 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_chair_02 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_chair_03 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_chair_04a 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_chair_04b 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_chair_05 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_chair_06 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_chair_07 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_chair_08 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.0,  useOffset = true },
	prop_chair_09 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_chair_10 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_chateau_chair_01 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.0,  useOffset = true },
	prop_cs_office_chair 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_direct_chair_01 		= { scenario = 'WORLD_HUMAN_SEAT_STEPS', verticalOffset = -0.5 },
	prop_direct_chair_02 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_gc_chair02 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.0,  useOffset = true },
	prop_off_chair_01 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_off_chair_03 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_off_chair_04 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.45, useOffset = true },
	prop_off_chair_04b 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.49, useOffset = true },
	prop_off_chair_04_s 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_off_chair_05 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.45},
	prop_old_deck_chair 		= { scenario = 'PROP_HUMAN_SEAT_DECKCHAIR', verticalOffset = 0.15, useOffset = true },
	prop_old_wood_chair 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.1, useOffset = true },
	prop_rock_chair_01 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.1, useOffset = true},
	prop_skid_chair_01 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.1, useOffset = true },
	prop_skid_chair_02 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.1, useOffset = true },
	prop_skid_chair_03 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.1, useOffset = true },
	prop_sol_chair 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_wheelchair_01 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.1, useOffset = true },
	prop_wheelchair_01_s 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	p_armchair_01_s 			= { scenario = 'PROP_HUMAN_SEAT_ARMCHAIR', verticalOffset = -0.48, useOffset = true },
	p_clb_officechair_s 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	p_dinechair_01_s 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	p_ilev_p_easychair_s 		= { scenario = 'PROP_HUMAN_SEAT_BUS_STOP_WAIT', verticalOffset = -0.52, useOffset = true },
	p_yacht_chair_01_s 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.0, useOffset = true },
	v_club_officechair 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	v_corp_bk_chair3 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.52, useOffset = true },
	v_corp_cd_chair 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	v_corp_offchair 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	v_ilev_chair02_ped 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.0, useOffset = true },
	v_ilev_hd_chair 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.6, useOffset = true },
	v_ilev_p_easychair 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.6, useOffset = true },
	v_ret_gc_chair03 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_table_04_chr 			= { scenario = 'PROP_HUMAN_SEAT_ARMCHAIR', verticalOffset = -0.55, useOffset = true },
	prop_table_05_chr 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.45, useOffset = true },
	prop_table_06_chr 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	v_ilev_leath_chr 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_table_01_chr_a 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.0, useOffset = true },
	prop_table_01_chr_b 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.0, useOffset = true },
	prop_table_02_chr 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_table_03b_chr 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_table_03_chr 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_torture_ch_01 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.1,  useOffset = true },
	v_ilev_fh_dineeamesa 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.55, useOffset = true },
	v_ilev_fh_kitchenstool 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.9,  useOffset = true },
	v_ilev_tort_stool 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.15, useOffset = true },

	-- SEAT (moble taki)
	hei_prop_yah_seat_01 		= { scenario = 'PROP_HUMAN_SEAT_ARMCHAIR', verticalOffset = -0.7, useOffset = true },
	hei_prop_yah_seat_02 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	hei_prop_yah_seat_03 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_waiting_seat_01 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_yacht_seat_01 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_yacht_seat_02 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_yacht_seat_03 			= { scenario = 'PROP_HUMAN_SEAT_ARMCHAIR', verticalOffset = -0.6, useOffset = true },
	prop_hobo_seat_01 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.3, useOffset = true },

	-- COUCH (moble kharab)
	prop_rub_couch01 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	miss_rub_couch_01 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_rub_couch02 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	prop_rub_couch03 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, useOffset = true },
	prop_rub_couch04 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },

	-- SOFA
	p_res_sofa_l_s 				= { scenario = 'PROP_HUMAN_SEAT_DECKCHAIR', verticalOffset = -0.5, useOffset = true },
	p_v_med_p_sofa_s 			= { scenario = 'WORLD_HUMAN_SEAT_STEPS', verticalOffset = -0.45, useOffset = true },
	p_yacht_sofa_01_s 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.0, useOffset = true },
	v_tre_sofa_mess_a_s 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	v_tre_sofa_mess_b_s 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	v_tre_sofa_mess_c_s 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },

	-- MISC
	prop_roller_car_01 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.3, useOffset = true },
	prop_roller_car_02 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },

	-- CUSTOM
	v_ret_gc_chair02			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.0, useOffset = true },
	v_serv_ct_chair02			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.0, useOffset = true },
	ex_Prop_OffChair_Exec_03	= { scenario = 'PROP_HUMAN_SEAT_ARMCHAIR', verticalOffset = 0.1, useOffset = true },
	ex_Prop_OffChair_Exec_02	= { scenario = 'PROP_HUMAN_SEAT_ARMCHAIR', verticalOffset = 0.1, useOffset = true },
	ex_Prop_OffChair_Exec_04	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.1, useOffset = true },
	V_Corp_Bk_Chair1			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.15, useOffset = true },
	Prop_Armchair_01			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	xm_Prop_x17_Avengerchair_02	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.1, useOffset = true },
	ex_mp_h_stn_ChairStrip_010	= { scenario = 'PROP_HUMAN_SEAT_ARMCHAIR', verticalOffset = -0.55, useOffset = true },
	xm_Lab_ChairArm_12			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },

	-- new
	ba_prop_int_edgy_stool		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.8, useOffset = true },
	v_corp_lazychair			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	hei_heist_stn_benchshort	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	v_corp_sidechair			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	v_ind_ss_chair01			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	v_ind_ss_chair2				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.0, useOffset = true },
	v_ilev_ph_bench				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	v_res_kitchnstool			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.7, useOffset = true },
	v_res_m_armchair			= { scenario = 'PROP_HUMAN_SEAT_ARMCHAIR', verticalOffset = -0.5, useOffset = true },
	v_res_mp_stripchair			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	v_res_tre_stool				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.05, useOffset = true },
	v_res_tt_sofa				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.1, useOffset = true },
	v_serv_bs_barbchair			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.8, useOffset = true },
	v_serv_bs_barbchair2		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.8, useOffset = true },
	v_serv_bs_barbchair3		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.8, useOffset = true },
	v_serv_bs_barbchair5		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.8, useOffset = true },
	prop_table_08_chr			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.3, useOffset = true },
	v_club_barchair				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	v_club_cc_stool				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	v_club_ch_armchair			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	v_club_ch_briefchair		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.0, useOffset = true },
	v_club_vuarmchair			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	apa_mp_h_din_chair_04		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.51, useOffset = true },
	apa_mp_h_din_chair_08		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	apa_mp_h_din_chair_09		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	apa_mp_h_din_chair_12		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	apa_mp_h_din_stool_04		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.85, useOffset = true },
	apa_mp_h_stn_chairarm_01	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	apa_mp_h_stn_chairarm_12	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	apa_mp_h_stn_chairarm_23	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	apa_mp_h_stn_chairarm_25	= { scenario = 'PROP_HUMAN_SEAT_DECKCHAIR', verticalOffset = -0.4, useOffset = true },
	apa_mp_h_stn_chairstool_12	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.48, useOffset = true },
	apa_mp_h_stn_chairstrip_01	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	apa_mp_h_stn_chairstrip_02	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.55, useOffset = true },
	apa_mp_h_stn_chairstrip_03	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	apa_mp_h_stn_chairstrip_04	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	apa_mp_h_stn_chairstrip_05	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	apa_mp_h_stn_chairstrip_06	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.55, useOffset = true },
	apa_mp_h_stn_chairstrip_07	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.55, useOffset = true },
	apa_mp_h_stn_chairstrip_08	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	apa_mp_h_stn_foot_stool_01	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	apa_mp_h_yacht_armchair_01	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	apa_mp_h_yacht_armchair_03	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	apa_mp_h_yacht_armchair_04	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	apa_mp_h_yacht_barstool_01	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.8, useOffset = true },
	apa_mp_h_yacht_stool_01		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.6, useOffset = true },
	apa_mp_h_yacht_strip_chair_01 = { scenario = 'PROP_HUMAN_SEAT_DECKCHAIR', verticalOffset = -0.45, useOffset = true },
	bkr_prop_biker_barstool_01	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.8, useOffset = true },
	bkr_prop_biker_barstool_02	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.8, useOffset = true },
	bkr_prop_biker_barstool_03	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.8, useOffset = true },
	bkr_prop_biker_barstool_04	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.8, useOffset = true },
	bkr_prop_biker_boardchair01	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.1, useOffset = true },
	bkr_prop_biker_chair_01		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	bkr_prop_biker_chairstrip_01 = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	bkr_prop_weed_chair_01a		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	bkr_prop_biker_chairstrip_02 = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	bkr_prop_clubhouse_chair_01	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.1, useOffset = true },
	bkr_prop_clubhouse_offchair_01a	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.1, useOffset = true },
	xm_lab_chairarm_25			= { scenario = 'PROP_HUMAN_SEAT_DECKCHAIR', verticalOffset = -0.45, useOffset = true },
	ex_mp_h_din_chair_04		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.53, useOffset = true },
	ex_mp_h_din_chair_08		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.53, useOffset = true },
	ex_mp_h_din_chair_09		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	ex_mp_h_din_chair_12		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	ex_mp_h_din_stool_04		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.85, useOffset = true },
	ex_mp_h_yacht_barstool_01	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.82, useOffset = true },
	ex_mp_h_off_chairstrip_01	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	ex_mp_h_off_easychair_01	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	ex_mp_h_stn_chairstrip_011	= { scenario = 'PROP_HUMAN_SEAT_ARMCHAIR', verticalOffset = -0.55, useOffset = true },
	ex_mp_h_stn_chairstrip_05	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	ex_mp_h_stn_chairstrip_07	= { scenario = 'PROP_HUMAN_SEAT_ARMCHAIR', verticalOffset = -0.55, useOffset = true },
	ex_prop_offchair_exec_01	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.1, useOffset = true },
	gr_dlc_gr_yacht_props_seat_01 = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.6, useOffset = true },
	gr_dlc_gr_yacht_props_seat_02 = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	gr_dlc_gr_yacht_props_seat_03 = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	gr_prop_gr_offchair_01a		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.1, useOffset = true },
	hei_heist_din_chair_01		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	hei_heist_din_chair_02		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	hei_heist_din_chair_03		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	hei_heist_din_chair_04		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	hei_heist_din_chair_05		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	hei_heist_din_chair_06		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	hei_heist_din_chair_08		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	hei_heist_din_chair_09		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	hei_heist_stn_chairarm_04	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	hei_heist_stn_chairarm_06	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	hei_heist_stn_chairstrip_01	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	hei_heist_stn_sofa3seat_01	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	imp_prop_impexp_offchair_01a = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.1, useOffset = true },
	sm_prop_offchair_smug_01	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.1, useOffset = true },
	sm_prop_offchair_smug_02	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = 0.1, useOffset = true },
	sum_mp_h_yacht_strip_chair_01 = { scenario = 'PROP_HUMAN_SEAT_DECKCHAIR', verticalOffset = -0.45, useOffset = true },
	h4_mp_h_yacht_strip_chair_01 = { scenario = 'PROP_HUMAN_SEAT_DECKCHAIR', verticalOffset = -0.45, useOffset = true },

	-- Aftabgir
	p_patio_lounger1_s 			= { scenario = 'PROP_HUMAN_SEAT_SUNLOUNGER', verticalOffset = -0.5 },
	prop_patio_lounger1 		= { scenario = 'PROP_HUMAN_SEAT_SUNLOUNGER', verticalOffset = -0.5 },


	-- addone (tu server nist)
	mp_b_stn_chairstrip_01		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	mp_b_stn_sofa3seat_01		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	apa_chairstrip_0x			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	ex_office_01b_sofa02		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	ex_office_01c_sofa02		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	ex_office2b_sofa01			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	ex_office2b_stripchair1		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	ex_office2b_stripchair2		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	ex_office2c_sofa01			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	ex_office_03b_stripchair1	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	ex_office_03b_stripchair2	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	ex_office_03c_chairstrip_01	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	ex_office_03c_stripchair_02	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	ex_warel_officebench		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	sf_mp_h_yacht_strip_chair_01 = { scenario = 'PROP_HUMAN_SEAT_DECKCHAIR', verticalOffset = -0.5 },
	v_43_officechair			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	v_16_low_lng_mesh_sofa1		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	v_16_low_lng_mesh_sofa2		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	v_16_low_lng_mesh_armchair	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	v_serv_bs_barbchair4		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.8, useOffset = true },
}

-- Bug sit
	-- p_soloffchair_s 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	-- prop_bench_07 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.6, useOffset = true },
	-- prop_clown_chair 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	-- apa_mp_h_stn_ChairArm_02	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	-- prop_hwbowl_pseat_6x1		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	-- apa_mp_h_stn_chairarm_03		= { scenario = 'PROP_HUMAN_SEAT_ARMCHAIR', verticalOffset = -0.6, useOffset = true },
	-- apa_mp_h_stn_chairarm_09		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	-- apa_mp_h_stn_chairarm_11	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	-- apa_mp_h_stn_chairarm_13	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	-- apa_mp_h_stn_chairarm_24	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	-- apa_mp_h_stn_chairarm_26	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	-- bkr_prop_clubhouse_armchair_01a	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	-- xm_lab_chairarm_02			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	-- xm_lab_chairarm_03			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	-- xm_lab_chairarm_11			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	-- xm_lab_chairarm_24			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	-- xm_lab_chairarm_26			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	-- xm_mp_h_stn_chairarm_13		= { scenario = 'PROP_HUMAN_SEAT_DECKCHAIR', verticalOffset = -0.45, useOffset = true },
	-- ex_mp_h_stn_chairarm_03		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	-- ex_mp_h_stn_chairarm_24		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	-- hei_heist_stn_chairarm_03	= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	-- prop_ld_farm_couch01 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	-- prop_ld_farm_couch02 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	-- prop_ld_farm_chair01 		= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	-- p_lev_sofa_s 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	-- v_ilev_m_sofa 				= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },
	-- v_res_tre_sofa_s 			= { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5 },



	-- WORLD_HUMAN_SEAT_STEPS           لش از پله می ره بالا 
	-- PROP_HUMAN_SEAT_ARMCHAIR         آرنج رو زانو 
	-- PROP_HUMAN_SEAT_BENCH            ساده
	-- PROP_HUMAN_SEAT_BUS_STOP_WAIT    دوتا آرنج رو زانو
	-- PROP_HUMAN_SEAT_CHAIR            ساده و منتظر
	-- PROP_HUMAN_SEAT_CHAIR_UPRIGHT    ساده و منتظر
	-- PROP_HUMAN_SEAT_CHAIR_MP_PLAYER  ساده و منتظر
	-- PROP_HUMAN_SEAT_DECKCHAIR        دست تو دماغ
	-- PROP_HUMAN_SEAT_STRIP_WATCH      دیسکو
	-- PROP_HUMAN_SEAT_SUNLOUNGER       افتابگیر