ConfigUWaterTr = {
    grabRadius = 100000,
    cancelRadius = 1000,
    randomPercend = 2,
    spawnObjectRadius = 30,
    drawLineRadius = 5,
    objectModel = 'ba_prop_battle_antique_box',
    carryRadius = 2,
    openBoxRadius = 2,
    openBoxTime = 30,
    uwfinderTime = 10,
    highAlarmDistance = 50,
    blackListJob = {
        police = true,
        ambulance = true,
        fbi = true,
        taxi = true,
        mechanic = true,
        mt = true,
        sheriff = true,
        weazel = true,
        detective = true,
        justice = true,
    },
    metalModel = 'w_am_digiscanner',
}