configSeat = {}

configSeat.MaxDistance = 1.5
configSeat.Debug = false

configSeat.Interactables = {

-- BENCH (nimkat 2 nafare)	
	'prop_bench_01a',
	'prop_bench_01b',
	'prop_bench_01c',
	'prop_bench_02',
	'prop_bench_03',
	'prop_bench_04',
	'prop_bench_05',
	'prop_bench_06',
	'prop_bench_08',
	'prop_bench_09',
	'prop_bench_10',
	'prop_bench_11',
	'prop_fib_3b_bench',
	'prop_ld_bench01',
	'prop_wait_bench_01',

-- CHAIR (sandali)
	'v_club_stagechair',
	'hei_prop_heist_off_chair',
	'hei_prop_hei_skid_chair',
	'prop_chair_01a',
	'prop_chair_01b',
	'prop_chair_02',
	'prop_chair_03',
	'prop_chair_04a',
	'prop_chair_04b',
	'prop_chair_05',
	'prop_chair_06',
	'prop_chair_07',
	'prop_chair_08',
	'prop_chair_09',
	'prop_chair_10',
	'prop_chateau_chair_01',
	'prop_cs_office_chair',
	'prop_direct_chair_01',
	'prop_direct_chair_02',
	'prop_gc_chair02',
	'prop_off_chair_01',
	'prop_off_chair_03',
	'prop_off_chair_04',
	'prop_off_chair_04b',
	'prop_off_chair_04_s',
	'prop_off_chair_05',
	'prop_old_deck_chair',
	'prop_old_wood_chair',
	'prop_rock_chair_01',
	'prop_skid_chair_01',
	'prop_skid_chair_02',
	'prop_skid_chair_03',
	'prop_sol_chair',
	'prop_wheelchair_01',
	'prop_wheelchair_01_s',
	'p_armchair_01_s',
	'p_clb_officechair_s',
	'p_dinechair_01_s',
	'p_ilev_p_easychair_s',
	'p_yacht_chair_01_s',
	'v_club_officechair',
	'v_corp_bk_chair3',
	'v_corp_cd_chair',
	'v_corp_offchair',
	'v_ilev_chair02_ped',
	'v_ilev_hd_chair',
	'v_ilev_p_easychair',
	'v_ret_gc_chair03',
	'prop_table_04_chr',
	'prop_table_05_chr',
	'prop_table_06_chr',
	'v_ilev_leath_chr',
	'prop_table_01_chr_a',
	'prop_table_01_chr_b',
	'prop_table_02_chr',
	'prop_table_03b_chr',
	'prop_table_03_chr',
	'prop_torture_ch_01',
	'v_ilev_fh_dineeamesa',
	'v_ilev_fh_kitchenstool',
	'v_ilev_tort_stool',

-- SEAT (moble taki)
	'hei_prop_yah_seat_01',
	'hei_prop_yah_seat_02',
	'hei_prop_yah_seat_03',
	'prop_waiting_seat_01',
	'prop_yacht_seat_01',
	'prop_yacht_seat_02',
	'prop_yacht_seat_03',
	'prop_hobo_seat_01',

-- COUCH (moble kharab)
	'prop_rub_couch01',
	'miss_rub_couch_01',
	'prop_rub_couch02',
	'prop_rub_couch03',
	'prop_rub_couch04',

-- SOFA
	'p_res_sofa_l_s',
	'p_v_med_p_sofa_s',
	'p_yacht_sofa_01_s',
	'v_tre_sofa_mess_a_s',
	'v_tre_sofa_mess_b_s',
	'v_tre_sofa_mess_c_s',

-- MISC
	'prop_roller_car_01',
	'prop_roller_car_02',

-- Custom
	'v_ret_gc_chair02',
	'v_serv_ct_chair02',
	'ex_Prop_OffChair_Exec_03',
	'ex_Prop_OffChair_Exec_02',
	'ex_Prop_OffChair_Exec_04',
	'V_Corp_Bk_Chair1',
	'Prop_Armchair_01',
	'xm_Prop_x17_Avengerchair_02',
	'ex_mp_h_stn_ChairStrip_010',
	'xm_Lab_ChairArm_12',

-- new
	'ba_prop_int_edgy_stool',
	'v_corp_lazychair',
	'hei_heist_stn_benchshort',
	'v_corp_sidechair',
	'v_ind_ss_chair01',
	'v_ind_ss_chair2',
	'v_ilev_ph_bench',
	'v_res_kitchnstool',
	'v_res_m_armchair',
	'v_res_mp_stripchair',
	'v_res_tre_stool',
	'v_res_tt_sofa',
	'v_serv_bs_barbchair',
	'v_serv_bs_barbchair2',
	'v_serv_bs_barbchair3',
	'v_serv_bs_barbchair5',
	'prop_table_08_chr',
	'v_club_barchair',
	'v_club_cc_stool',
	'v_club_ch_armchair',
	'v_club_ch_briefchair',
	'v_club_vuarmchair',
	'apa_mp_h_din_chair_04',
	'apa_mp_h_din_chair_08',
	'apa_mp_h_din_chair_09',
	'apa_mp_h_din_chair_12',
	'apa_mp_h_din_stool_04',
	'apa_mp_h_stn_chairarm_01',
	'apa_mp_h_stn_chairarm_12',
	'apa_mp_h_stn_chairarm_23',
	'apa_mp_h_stn_chairarm_25',
	'apa_mp_h_stn_chairstool_12',
	'apa_mp_h_stn_chairstrip_01',
	'apa_mp_h_stn_chairstrip_02',
	'apa_mp_h_stn_chairstrip_03',
	'apa_mp_h_stn_chairstrip_04',
	'apa_mp_h_stn_chairstrip_05',
	'apa_mp_h_stn_chairstrip_06',
	'apa_mp_h_stn_chairstrip_07',
	'apa_mp_h_stn_chairstrip_08',
	'apa_mp_h_stn_foot_stool_01',
	'apa_mp_h_yacht_armchair_01',
	'apa_mp_h_yacht_armchair_03',
	'apa_mp_h_yacht_armchair_04',
	'apa_mp_h_yacht_barstool_01',
	'apa_mp_h_yacht_stool_01',
	'apa_mp_h_yacht_strip_chair_01',
	'bkr_prop_biker_barstool_01',
	'bkr_prop_biker_barstool_02',
	'bkr_prop_biker_barstool_03',
	'bkr_prop_biker_barstool_04',
	'bkr_prop_biker_boardchair01',
	'bkr_prop_biker_chair_01',
	'bkr_prop_biker_chairstrip_01',
	'bkr_prop_weed_chair_01a',
	'bkr_prop_biker_chairstrip_02',
	'bkr_prop_clubhouse_chair_01',
	'bkr_prop_clubhouse_offchair_01a',
	'xm_lab_chairarm_25',
	'ex_mp_h_din_chair_04',
	'ex_mp_h_din_chair_08',
	'ex_mp_h_din_chair_09',
	'ex_mp_h_din_chair_12',
	'ex_mp_h_din_stool_04',
	'ex_mp_h_yacht_barstool_01',
	'ex_mp_h_off_chairstrip_01',
	'ex_mp_h_off_easychair_01',
	'ex_mp_h_stn_chairstrip_01',
	'ex_mp_h_stn_chairstrip_011',
	'ex_mp_h_stn_chairstrip_05',
	'ex_mp_h_stn_chairstrip_07',
	'ex_prop_offchair_exec_01',
	'gr_dlc_gr_yacht_props_seat_01',
	'gr_dlc_gr_yacht_props_seat_02',
	'gr_dlc_gr_yacht_props_seat_03',
	'gr_prop_gr_offchair_01a',
	'hei_heist_din_chair_01',
	'hei_heist_din_chair_02',
	'hei_heist_din_chair_03',
	'hei_heist_din_chair_04',
	'hei_heist_din_chair_05',
	'hei_heist_din_chair_06',
	'hei_heist_din_chair_08',
	'hei_heist_din_chair_09',
	'hei_heist_stn_chairarm_01',
	'hei_heist_stn_chairarm_04',
	'hei_heist_stn_chairarm_06',
	'hei_heist_stn_chairstrip_01',
	'hei_heist_stn_sofa3seat_01',
	'imp_prop_impexp_offchair_01a',
	'sm_prop_offchair_smug_01',
	'sm_prop_offchair_smug_02',
	'sum_mp_h_yacht_strip_chair_01',
	'mp_b_stn_chairstrip_01',
	'mp_b_stn_sofa3seat_01',
	'apa_chairstrip_0x',
	'ex_office_01b_sofa02',
	'ex_office_01c_sofa02',
	'ex_office2b_sofa01',
	'ex_office2b_stripchair1',
	'ex_office2b_stripchair2',
	'ex_office2c_sofa01',
	'ex_office_03b_stripchair1',
	'ex_office_03b_stripchair2',
	'ex_office_03c_chairstrip_01',
	'ex_office_03c_stripchair_02',
	'ex_warel_officebench',
	'h4_mp_h_yacht_strip_chair_01',
	'sf_mp_h_yacht_strip_chair_01',
	'v_43_officechair',
	'v_16_low_lng_mesh_sofa1',
	'v_16_low_lng_mesh_sofa2',
	'v_16_low_lng_mesh_armchair',
	'v_serv_bs_barbchair4',
	'p_patio_lounger1_s', 
	'prop_patio_lounger1',
}

configSeat.beds = {
	'v_med_bed1',
	'v_med_bed2',
	'v_res_msonbed',
	'v_res_msonbed_s',
	'p_lestersbed_s',
	'p_mbbed_s',
	'gr_prop_bunker_bed_01',
	'v_res_mdbed',
}

-- Bug sit
-- 'p_soloffchair_s',
	-- 'prop_bench_07',
	-- 'prop_clown_chair',
	-- 'apa_mp_h_stn_ChairArm_02',
	-- 'prop_hwbowl_pseat_6x1',
	-- 'apa_mp_h_stn_chairarm_03',
	-- 'apa_mp_h_stn_chairarm_09',
	-- 'apa_mp_h_stn_chairarm_11',
	-- 'apa_mp_h_stn_chairarm_13',
	-- 'apa_mp_h_stn_chairarm_24',
	-- 'apa_mp_h_stn_chairarm_26',
	-- 'bkr_prop_clubhouse_armchair_01a',
	-- 'xm_lab_chairarm_02',
	-- 'xm_lab_chairarm_03',
	-- 'xm_lab_chairarm_11',
	-- 'xm_lab_chairarm_24',
	-- 'xm_lab_chairarm_26',
	-- 'xm_mp_h_stn_chairarm_13',
	-- 'ex_mp_h_stn_chairarm_03',
	-- 'ex_mp_h_stn_chairarm_24',
	-- 'hei_heist_stn_chairarm_03',	
	-- 'prop_ld_farm_couch01',
	-- 'prop_ld_farm_couch02',	
	-- 'prop_ld_farm_chair01',
	-- 'p_lev_sofa_s',
	-- 'v_ilev_m_sofa',
	-- 'v_res_tre_sofa_s',

-- bug bed
	-- 'p_v_res_tt_bed_s',
	-- 'apa_mp_h_bed_double_08',
	-- 'apa_mp_h_bed_double_09',
	-- 'apa_mp_h_bed_wide_05',
	-- 'apa_mp_h_bed_with_table_02',
	-- 'apa_mp_h_yacht_bed_01',
	-- 'apa_mp_h_yacht_bed_02',
	-- 'bkr_prop_biker_campbed_01',
	-- 'ex_prop_exec_bed_01',
	-- 'hei_heist_bed_double_08',